CinemaManager/Controllers/UsersController.cs
using CinemaManager.Models;
using CinemaManager.Repositories;
using Microsoft.AspNetCore.Mvc;

namespace CinemaManager.Controllers
{
    public class UsersController : Controller
    {
        private readonly IUserRepository _userRepository;

        public UsersController(IUserRepository userRepository)
        {
            _userRepository = userRepository;
        }

        public async Task<IActionResult> Index()
        {
            var users = await _userRepository.GetUsersAsync();
            return View(users);
        }

        public IActionResult Create()
        {
            return View();
        }

        public async Task<IActionResult> Update(int id)
        {
            var user = await _userRepository.GetUserByIdAsync(id);
            return View(user);
        }

        public async Task<IActionResult> ConfirmRemove(int id)
        {
            var user = await _userRepository.GetUserByIdAsync(id);
            return View(user);
        }

        [HttpPost]
        public async Task<IActionResult> Create(UserModel userModel)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var success = await _userRepository.CheckIfUserAlreadyExistsAsync(userModel);

                    if (success)
                    {
                        TempData["ErrorMessage"] = MessagesModel.EmailOrLoginAlreadyRegistered;

                        return View(userModel);
                    }

                    success = await _userRepository.AddUserAsync(userModel);

                    if (success)
                    {
                        TempData["SuccessMessage"] = MessagesModel.UserSuccesfulyCreated;
                    }
                    else
                    {
                        TempData["ErrorMessage"] = MessagesModel.UnableToCreateUser;
                    }

                    return RedirectToAction("Index");
                }

                return View(userModel);
            }
            catch (Exception ex)
            {
                TempData["ErrorMessage"] = $"{MessagesModel.UnableToCreateUser} Erro: {ex.Message}";

                return RedirectToAction("Index");
            }
        }

        [HttpPost]
        public async Task<IActionResult> Update(UserWithoutPasswordModel userWithoutPasswordModel)
        {
            try
            {
                UserModel? userModel = null;

                if (ModelState.IsValid)
                {
                    userModel = new UserModel
                    {
                        Id = userWithoutPasswordModel.Id,
                        Name = userWithoutPasswordModel.Name,
                        Email = userWithoutPasswordModel.Email,
                        Login = userWithoutPasswordModel.Login,
                        Perfil = userWithoutPasswordModel.Perfil
                    };

                    var success = await _userRepository.CheckIfUserAlreadyExistsAsync(userModel);

                    if (success)
                    {
                        TempData["ErrorMessage"] = MessagesModel.EmailOrLoginAlreadyRegistered;

                        return View(userModel);
                    }

                    success = await _userRepository.UpdateUserAsync(userModel);

                    if (success)
                    {
                        TempData["SuccessMessage"] = MessagesModel.UserSuccesfulyUpdated;
                    }
                    else
                    {
                        TempData["ErrorMessage"] = MessagesModel.UnableToUpdateUser;
                    }

                    return RedirectToAction("Index");
                }

                return View(userModel);
            }
            catch (Exception ex)
            {
                TempData["ErrorMessage"] = $"{MessagesModel.UnableToUpdateUser} Erro: {ex.Message}";

                return RedirectToAction("Index");
            }
        }


        [HttpPost]
        public async Task<IActionResult> Remove(int id)
        {
            try
            {
                var success = await _userRepository.RemoveUserAsync(id);

                if (success)
                {
                    TempData["SuccessMessage"] = MessagesModel.UserSuccesfulyRemoved;
                }
                else
                {
                    TempData["ErrorMessage"] = MessagesModel.UnableToRemoveUser;
                }

                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                TempData["ErrorMessage"] = $"{MessagesModel.UnableToRemoveUser} Erro: {ex.Message}";

                return RedirectToAction("Index");
            }
        }
    }
}

CinemaManager/Views/Users/ConfirmRemove.cshtml
@model UserModel
@{
    ViewData["Title"] = "Remover Usuário";
}

<br />

<form asp-controller="Users" asp-action="Remove" asp-route-id="@Model.Id" method="post">
    <div class="text-center">
        <h3>Tem certeza que deseja remover o usuário (@Model.Name)?</h3>
        <br />

        <a class="btn btn-link" role="button" asp-controller="Users" asp-action="Index">Cancelar</a>
        <button type="submit" class="btn btn-danger">Confirmar</button>
    </div>
</form>

CinemaManager/Views/Users/Create.cshtml
@using CinemaManager.Enums
@model UserModel
@{
    ViewData["Title"] = "Novo Usuário";
}

<h1 class="display-4">Novo Usuário</h1>

@if (TempData["ErrorMessage"] is not null)
{
    <div class="alert alert-danger" role="alert">
        <span>@TempData["ErrorMessage"]</span>
        <button type="button" class="btn btn-danger btn-sm close-alert" arial-label="close">X</button>
    </div>
}

<form asp-controller="Users" asp-action="Create" method="post">
    <div class="form-group">
        <label for="name">Nome</label>
        <input type="text" asp-for="Name" class="form-control" id="name" placeholder="Nome">
        @Html.ValidationMessageFor(x => x.Name)
    </div>
    <br />

    <div class="form-group">
        <label for="email">E-mail</label>
        <input type="email" asp-for="Email" class="form-control" id="email" placeholder="E-mail">
        @Html.ValidationMessageFor(x => x.Email)
    </div>
    <br />

    <div class="form-group">
        <label for="password">Senha</label>
        <input type="password" asp-for="Password" class="form-control" id="password" placeholder="Senha">
        @Html.ValidationMessageFor(x => x.Password)
    </div>
    <br />

    <div class="form-group">
        <label for="login">Login</label>
        <input type="text" asp-for="Login" class="form-control" id="login" placeholder="Login">
        @Html.ValidationMessageFor(x => x.Login)
    </div>
    <br />

    <div class="form-group">
        <label for="perfil">Perfil</label>
        <select asp-for="Perfil" class="form-control" id="perfil">
            <option value="">Selecione</option>
            <option value="@PerfilEnum.Admin">Administrador</option>
            <option value="@PerfilEnum.User">Usuário</option>
        </select>
        @Html.ValidationMessageFor(x => x.Perfil)
    </div>
    <br />

    <button type="submit" class="btn btn-primary form-control">Adicionar</button>
    <a class="btn btn-link form-control" role="button" asp-controller="Users" asp-action="Index">Voltar</a>
</form>

CinemaManager/Views/Users/Index.cshtml
@model IEnumerable<UserModel>
@{
    ViewData["Title"] = "Usuários";
}

<h1 class="display-4">Usuários</h1>

@if (TempData["SuccessMessage"] is not null)
{
    <div class="alert alert-success" role="alert">
        <span>@TempData["SuccessMessage"]</span>
        <button type="button" class="btn btn-success btn-sm close-alert" arial-label="close">X</button>
    </div>
}

@if (TempData["ErrorMessage"] is not null)
{
    <div class="alert alert-danger" role="alert">
        <span>@TempData["ErrorMessage"]</span>
        <button type="button" class="btn btn-danger btn-sm close-alert" arial-label="close">X</button>
    </div>
}

<div>
    <a class="btn btn-primary" role="button" asp-controller="Users" asp-action="Create">Novo Usuário</a>
</div>
<br />

<table class="table" id="table">
    <thead>
        <tr>
            <th scope="col">Id</th>
            <th scope="col">Nome</th>
            <th scope="col">E-mail</th>
            <th scope="col">Login</th>
            <th scope="col">Perfil</th>
            <th scope="col">Criado em</th>
            <th scope="col"></th>
        </tr>
    </thead>

    <tbody>
        @if (Model is not null && Model.Any())
        {
            foreach (var users in Model)
            {
                <tr class="align-middle">
                    <th scope="row">@users.Id</th>
                    <td>@users.Name</td>
                    <td>@users.Email</td>
                    <td>@users.Login</td>
                    <td>@(users.Perfil == CinemaManager.Enums.PerfilEnum.Admin ? "Administrador" : "Usuário")</td>
                    <td>@users.CreatedAt</td>
                    <td>
                        <div>
                            <a class="btn btn-primary" role="button" asp-controller="Users" asp-action="Update" asp-route-id="@users.Id">Atualizar</a>
                            <a class="btn btn-danger" role="button" asp-controller="Users" asp-action="ConfirmRemove" asp-route-id="@users.Id">Remover</a>
                        </div>
                    </td>
                </tr>
            }
        }
    </tbody>
</table>

CinemaManager/Views/Users/Update.cshtml
@using CinemaManager.Enums
@model UserModel
@{
    ViewData["Title"] = "Atualizar Usuário";
}

<h1 class="display-4">Atualizar Usuário</h1>

@if (TempData["ErrorMessage"] is not null)
{
    <div class="alert alert-danger" role="alert">
        <span>@TempData["ErrorMessage"]</span>
        <button type="button" class="btn btn-danger btn-sm close-alert" arial-label="close">X</button>
    </div>
}

<form asp-controller="Users" asp-action="Update" method="post">
    <div class="form-group">
        <label for="name">Nome</label>
        <input type="text" asp-for="Name" class="form-control" id="name" placeholder="Nome">
        @Html.ValidationMessageFor(x => x.Name)
    </div>
    <br />

    <div class="form-group">
        <label for="email">E-mail</label>
        <input type="email" asp-for="Email" class="form-control" id="email" placeholder="E-mail">
        @Html.ValidationMessageFor(x => x.Email)
    </div>
    <br />

    <div class="form-group">
        <label for="login">Login</label>
        <input type="text" asp-for="Login" class="form-control" id="login" placeholder="Login">
        @Html.ValidationMessageFor(x => x.Login)
    </div>
    <br />

    <div class="form-group">
        <label for="perfil">Perfil</label>
        <select asp-for="Perfil" class="form-control" id="perfil">
            <option value="">Selecione</option>
            <option value="@PerfilEnum.Admin">Administrador</option>
            <option value="@PerfilEnum.User">Usuário</option>
        </select>
        @Html.ValidationMessageFor(x => x.Perfil)
    </div>
    <br />

    <button type="submit" class="btn btn-primary form-control">Atualizar</button>
    <a class="btn btn-link form-control" role="button" asp-controller="Users" asp-action="Index">Voltar</a>
</form>