CinemaManager/Controllers/SessionController.cs
using CinemaManager.Models;
using CinemaManager.Repositories;
using Microsoft.AspNetCore.Mvc;

namespace CinemaManager.Controllers
{
    public class SessionController : Controller
    {
        private readonly ISessionRepository _sessionRepository;

        public SessionController(ISessionRepository sessionRepository)
        {
            _sessionRepository = sessionRepository;
        }

        public async Task<IActionResult> Index()
        {
            var sessions = await _sessionRepository.GetSessionsAsync();
            return View(sessions);
        }

        public async Task<IActionResult> IndexForUser()
        {
            var sessions = await _sessionRepository.GetSessionsAsync();
            return View(sessions);
        }

        public IActionResult Create()
        {
            return View();
        }

        public async Task<IActionResult> ConfirmRemove(int id)
        {
            var movie = await _sessionRepository.GetSessionByIdAsync(id);
            return View(movie);
        }

        [HttpPost]
        public async Task<IActionResult> Create(SessionModel sessionModel)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var success = _sessionRepository.CheckIfSessionStartDateIsValid(sessionModel);

                    if (!success)
                    {
                        TempData["ErrorMessage"] = MessagesModel.InvalidSessionStartDate;

                        return View(sessionModel);
                    }

                    success = _sessionRepository.CheckIfMovieExists(sessionModel.MovieTitle);

                    if (!success)
                    {
                        TempData["ErrorMessage"] = MessagesModel.MovieNotFound;

                        return View(sessionModel);
                    }

                    success = _sessionRepository.CheckIfTheaterExists(sessionModel.TheaterName);

                    if (!success)
                    {
                        TempData["ErrorMessage"] = MessagesModel.TheaterNotFound;

                        return View(sessionModel);
                    }

                    success = await _sessionRepository.CheckIfSessionIsAlreadyAllocatedAsync(sessionModel);

                    if (success)
                    {
                        TempData["SuccessMessage"] = MessagesModel.SessionAlreadyAllocated;
                    }

                    success = await _sessionRepository.AddSessionAsync(sessionModel);

                    if (success)
                    {
                        TempData["SuccessMessage"] = MessagesModel.SessionSuccesfulyCreated;
                    }
                    else
                    {
                        TempData["ErrorMessage"] = MessagesModel.UnableToCreateSession;
                    }

                    return RedirectToAction("Index");
                }

                return View(sessionModel);
            }
            catch (Exception ex)
            {
                TempData["ErrorMessage"] = $"{MessagesModel.UnableToCreateSession} Erro: {ex.Message}";

                return RedirectToAction("Index");
            }
        }

        [HttpPost]
        public async Task<IActionResult> Remove(int id)
        {
            try
            {
                var success = await _sessionRepository.CheckIfSessionCanBeRemovedAsync(id);

                if (!success)
                {
                    TempData["ErrorMessage"] = MessagesModel.SessionCannotBeRemoved;

                    return RedirectToAction("Index");
                }

                success = await _sessionRepository.RemoveSessionAsync(id);

                if (success)
                {
                    TempData["SuccessMessage"] = MessagesModel.SessionSuccesfulyRemoved;
                }
                else
                {
                    TempData["ErrorMessage"] = MessagesModel.UnableToRemoveSession;
                }

                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                TempData["ErrorMessage"] = $"{MessagesModel.UnableToRemoveSession} Erro: {ex.Message}";

                return RedirectToAction("Index");
            }
        }
    }
}

CinemaManager/Views/Session/ConfirmRemove.cshtml
@model SessionModel
@{
    ViewData["Title"] = "Remover Sessão";
}

<br />

<form asp-controller="Session" asp-action="Remove" asp-route-id="@Model.Id" method="post">
    <div class="text-center">
        <h3>Tem certeza que deseja remover a sessão (@Model.Id)?</h3>
        <br />

        <a class="btn btn-link" role="button" asp-controller="Session" asp-action="Index">Cancelar</a>
        <button type="submit" class="btn btn-danger">Confirmar</button>
    </div>
</form>

CinemaManager/Views/Session/Create.cshtml
@using CinemaManager.Enums
@model SessionModel
@{
    ViewData["Title"] = "Nova Sessão";
}

<h1 class="display-4">Nova Sessão</h1>

@if (TempData["ErrorMessage"] is not null)
{
    <div class="alert alert-danger" role="alert">
        <span>@TempData["ErrorMessage"]</span>
        <button type="button" class="btn btn-danger btn-sm close-alert" arial-label="close">X</button>
    </div>
}

<form asp-controller="Session" asp-action="Create" method="post">
    <div class="form-group">
        <label for="date">Data</label>
        <input type="date" asp-for="Date" class="form-control" id="date" placeholder="Data da sessão">
        @Html.ValidationMessageFor(x => x.Date)
    </div>
    <br />

    <div class="form-group">
        <label for="startTime">Horário inicial</label>
        <input type="datetime-local" asp-for="StartTime" class="form-control" id="startTime" placeholder="Horário do início do filme">
        @Html.ValidationMessageFor(x => x.StartTime)
    </div>
    <br />

    <div class="form-group">
        <label for="ticketValue">Valor do ingresso</label>
        <input type="text" asp-for="TicketValue" class="form-control" id="ticketValue" placeholder="Ex.: 20 ou 20,00 ou R$ 20,00">
        @Html.ValidationMessageFor(x => x.TicketValue)
    </div>
    <br />

    <div class="form-group">
        <label for="typeOfAnimation">Tipo da animação</label>
        <select asp-for="TypeOfAnimation" class="form-control" id="typeOfAnimation">
            <option value="">Selecione</option>
            <option value="@TypeOfAnimationEnum.ThreeDimensional">3D</option>
            <option value="@TypeOfAnimationEnum.TwoDimensional">2D</option>
        </select>
        @Html.ValidationMessageFor(x => x.TypeOfAnimation)
    </div>
    <br />

    <div class="form-group">
        <label for="typeOfAudio">Tipo da áudio</label>
        <select asp-for="AudioType" class="form-control" id="typeOfAudio">
            <option value="">Selecione</option>
            <option value="@AudioTypeEnum.Original">Originial</option>
            <option value="@AudioTypeEnum.Dubbed">Dublado</option>
        </select>
        @Html.ValidationMessageFor(x => x.AudioType)
    </div>
    <br />

    <div class="form-group">
        <label for="movie">Filme</label>
        <input type="text" asp-for="MovieTitle" class="form-control" id="movie" placeholder="Título do filme">
        @Html.ValidationMessageFor(x => x.MovieTitle)
    </div>
    <br />

    <div class="form-group">
        <label for="theater">Sala</label>
        <input type="text" asp-for="TheaterName" class="form-control" id="theater" placeholder="Nome da sala">
        @Html.ValidationMessageFor(x => x.TheaterName)
    </div>
    <br />

    <button type="submit" class="btn btn-primary form-control">Adicionar</button>
    <a class="btn btn-link form-control" role="button" asp-controller="Session" asp-action="Index">Voltar</a>
</form>

CinemaManager/Views/Session/Index.cshtml
@model IEnumerable<SessionModel>
@{
    ViewData["Title"] = "Sessões";
}

<h1 class="display-4">Sessões</h1>

@if (TempData["SuccessMessage"] is not null)
{
    <div class="alert alert-success" role="alert">
        <span>@TempData["SuccessMessage"]</span>
        <button type="button" class="btn btn-success btn-sm close-alert" arial-label="close">X</button>
    </div>
}

@if (TempData["ErrorMessage"] is not null)
{
    <div class="alert alert-danger" role="alert">
        <span>@TempData["ErrorMessage"]</span>
        <button type="button" class="btn btn-danger btn-sm close-alert" arial-label="close">X</button>
    </div>
}

<div>
    <a class="btn btn-primary" role="button" asp-controller="Session" asp-action="Create">Nova Sessão</a>
</div>
<br />

<table class="table" id="table">
    <thead>
        <tr>
            <th scope="col">Data</th>
            <th scope="col">Horário Início</th>
            <th scope="col">Horário Fim</th>
            <th scope="col">Valor Ingresso</th>
            <th scope="col">Tipo Animação</th>
            <th scope="col">Tipo de Audio</th>
            <th scope="col">Filme</th>
            <th scope="col">Sala</th>
            <th scope="col"></th>
        </tr>
    </thead>

    <tbody>
        @if (Model is not null && Model.Any())
        {
            foreach (var session in Model)
            {
                <tr class="align-middle">
                    <td>@session.Date.ToString("MM/dd/yyyy")</td>
                    <td>@session.StartTime</td>
                    <td>@session.EndTime</td>
                    <td>@session.TicketValue</td>
                    <td>@(session.TypeOfAnimation == CinemaManager.Enums.TypeOfAnimationEnum.ThreeDimensional ? "3D" : "2D")</td>
                    <td>@(session.AudioType == CinemaManager.Enums.AudioTypeEnum.Original ? "Original" : "Dublado")</td>
                    <td>@session.MovieTitle</td>
                    <td>@session.TheaterName</td>
                    <td>
                        <div>
                            <a class="btn btn-danger" role="button" asp-controller="Session" asp-action="ConfirmRemove" asp-route-id="@session.Id">Remover</a>
                        </div>
                    </td>
                </tr>
            }
        }
    </tbody>
</table>

CinemaManager/Views/Session/IndexForUser.cshtml
@model IEnumerable<SessionModel>
@{
    ViewData["Title"] = "Sessões";
}

<h1 class="display-4">Sessões</h1>

<table class="table" id="table">
    <thead>
        <tr>
            <th scope="col">Data</th>
            <th scope="col">Horário Início</th>
            <th scope="col">Horário Fim</th>
            <th scope="col">Valor Ingresso</th>
            <th scope="col">Tipo Animação</th>
            <th scope="col">Tipo de Audio</th>
            <th scope="col">Filme</th>
            <th scope="col">Sala</th>
        </tr>
    </thead>

    <tbody>
        @if (Model is not null && Model.Any())
        {
            foreach (var session in Model)
            {
                <tr class="align-middle">
                    <td>@session.Date</td>
                    <td>@session.StartTime</td>
                    <td>@session.EndTime</td>
                    <td>@session.TicketValue</td>
                    <td>@(session.TypeOfAnimation == CinemaManager.Enums.TypeOfAnimationEnum.ThreeDimensional ? "3D" : "2D")</td>
                    <td>@(session.AudioType == CinemaManager.Enums.AudioTypeEnum.Original ? "Original" : "Dublado")</td>
                    <td>@session.MovieTitle</td>
                    <td>@session.TheaterName</td>
                </tr>
            }
        }
    </tbody>
</table>