CinemaManager/Controllers/MoviesController.cs
using CinemaManager.Models;
using CinemaManager.Repositories;
using Microsoft.AspNetCore.Mvc;

namespace CinemaManager.Controllers
{
    public class MoviesController : Controller
    {
        private readonly IMoviesRepository _moviesRepository;

        public MoviesController(IMoviesRepository moviesRepository)
        {
            _moviesRepository = moviesRepository;
        }

        public async Task<IActionResult> Index()
        {
            var movies = await _moviesRepository.GetMoviesAsync();
            return View(movies);
        }

        public async Task<IActionResult> IndexForUser()
        {
            var movies = await _moviesRepository.GetMoviesAsync();
            return View(movies);
        }

        public IActionResult Create()
        {
            return View();
        }

        public async Task<IActionResult> Update(int id)
        {
            var movie = await _moviesRepository.GetMovieByIdAsync(id);
            return View(movie);
        }

        public async Task<IActionResult> ConfirmRemove(int id)
        {
            var movie = await _moviesRepository.GetMovieByIdAsync(id);
            return View(movie);
        }

        [HttpPost]
        public async Task<IActionResult> Create(MoviesModel moviesModel)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var success = await _moviesRepository.CheckIfMovieIsAlreadyRegisteredAsync(moviesModel);

                    if (success)
                    {
                        TempData["ErrorMessage"] = MessagesModel.MovieAlreadyRegistered;

                        return View(moviesModel);
                    }

                    success = await _moviesRepository.AddMovieAsync(moviesModel);

                    if (success)
                    {
                        TempData["SuccessMessage"] = MessagesModel.MovieSuccesfulyCreated;
                    }
                    else
                    {
                        TempData["ErrorMessage"] = MessagesModel.UnableToCreateMovie;
                    }

                    return RedirectToAction("Index");
                }

                return View(moviesModel);
            }
            catch (Exception ex)
            {
                TempData["ErrorMessage"] = $"{MessagesModel.UnableToCreateMovie} Erro: {ex.Message}";

                return RedirectToAction("Index");
            }
        }

        [HttpPost]
        public async Task<IActionResult> Update(MoviesModel moviesModel)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var success = await _moviesRepository.CheckIfMovieIsAlreadyRegisteredAsync(moviesModel);

                    if (success)
                    {
                        TempData["ErrorMessage"] = MessagesModel.MovieAlreadyRegistered;

                        return View(moviesModel);
                    }

                    success = await _moviesRepository.UpdateMovieAsync(moviesModel);

                    if (success)
                    {
                        TempData["SuccessMessage"] = MessagesModel.MovieSuccesfulyUpdated;
                    }
                    else
                    {
                        TempData["ErrorMessage"] = MessagesModel.UnableToUpdateMovie;
                    }

                    return RedirectToAction("Index");
                }

                return View(moviesModel);
            }
            catch (Exception ex)
            {
                TempData["ErrorMessage"] = $"{MessagesModel.UnableToUpdateMovie} Erro: {ex.Message}";

                return RedirectToAction("Index");
            }
        }

        [HttpPost]
        public async Task<IActionResult> Remove(int id)
        {
            try
            {
                var success = await _moviesRepository.CheckIfMovieIsLinkedToAnySessionAsync(id);

                if (success)
                {
                    TempData["ErrorMessage"] = MessagesModel.MovieLinkedToASession;

                    return RedirectToAction("Index");
                }

                success = await _moviesRepository.RemoveMovieAsync(id);

                if (success)
                {
                    TempData["SuccessMessage"] = MessagesModel.MovieSuccesfulyRemoved;
                }
                else
                {
                    TempData["ErrorMessage"] = MessagesModel.UnableToRemoveMovie;
                }

                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                TempData["ErrorMessage"] = $"{MessagesModel.UnableToRemoveMovie} Erro: {ex.Message}";

                return RedirectToAction("Index");
            }
        }
    }
}

CinemaManager/Views/Movies/ConfirmRemove.cshtml
@model MoviesModel
@{
    ViewData["Title"] = "Remover Filme";
}

<br />

<form asp-controller="Movies" asp-action="Remove" asp-route-id="@Model.Id" method="post">
    <div class="text-center">
        <h3>Tem certeza que deseja remover o filme (@Model.Title)?</h3>
        <br />

        <a class="btn btn-link" role="button" asp-controller="Movies" asp-action="Index">Cancelar</a>
        <button type="submit" class="btn btn-danger">Confirmar</button>
    </div>
</form>

CinemaManager/Views/Movies/Create.cshtml
@model MoviesModel
@{
    ViewData["Title"] = "Novo Filme";
}

<h1 class="display-4">Novo Filme</h1>

@if (TempData["ErrorMessage"] is not null)
{
    <div class="alert alert-danger" role="alert">
        <span>@TempData["ErrorMessage"]</span>
        <button type="button" class="btn btn-danger btn-sm close-alert" arial-label="close">X</button>
    </div>
}

<form asp-controller="Movies" asp-action="Create" method="post">
    <div class="form-group">
        <label for="imageLink">Imagem</label>
        <input type="text" asp-for="Image" class="form-control" id="imageLink" placeholder="Link da Imagem">
        @Html.ValidationMessageFor(x => x.Image)
    </div>
    <br />

    <div class="form-group">
        <label for="title">Título</label>
        <input type="text" asp-for="Title" class="form-control" id="title" placeholder="Título do filme">
        @Html.ValidationMessageFor(x => x.Title)
    </div>
    <br />

    <div class="form-group">
        <label for="description">Descrição</label>
        <input type="text" asp-for="Description" class="form-control" id="description" placeholder="Descrição do filme">
        @Html.ValidationMessageFor(x => x.Description)
    </div>
    <br />

    <div class="form-group">
        <label for="duration">Duração</label>
        <input type="datetime" asp-for="Duration" class="form-control" id="duration" placeholder="Ex.: 30min ou 1h ou 1h 30min">
        @Html.ValidationMessageFor(x => x.Duration)
    </div>
    <br />

    <button type="submit" class="btn btn-primary form-control">Adicionar</button>
    <a class="btn btn-link form-control" role="button" asp-controller="Movies" asp-action="Index">Voltar</a>
</form>

CinemaManager/Views/Movies/Index.cshtml
@model IEnumerable<MoviesModel>
@{
    ViewData["Title"] = "Filmes";
}

<h1 class="display-4">Filmes</h1>

@if (TempData["SuccessMessage"] is not null)
{
    <div class="alert alert-success" role="alert">
        <span>@TempData["SuccessMessage"]</span>
        <button type="button" class="btn btn-success btn-sm close-alert" arial-label="close">X</button>
    </div>
}

@if (TempData["ErrorMessage"] is not null)
{
    <div class="alert alert-danger" role="alert">
        <span>@TempData["ErrorMessage"]</span>
        <button type="button" class="btn btn-danger btn-sm close-alert" arial-label="close">X</button>
    </div>
}

<div>
    <a class="btn btn-primary" role="button" asp-controller="Movies" asp-action="Create">Novo Filme</a>
</div>
<br />

<table class="table" id="table">
    <thead>
        <tr>
            <th scope="col" style="width: 25%">Título</th>
            <th scope="col" style="width: 50%">Descrição</th>
            <th scope="col">Duração</th>
            <th scope="col">Operações</th>
        </tr>
    </thead>

    <tbody>
        @if (Model is not null && Model.Any())
        {
            foreach (var movie in Model)
            {
                <tr class="align-middle">
                    <td>@movie.Title</td>
                    <td>@movie.Description</td>
                    <td>@movie.Duration</td>
                    <td>
                        <div>
                            <a class="btn btn-primary" role="button" asp-controller="Movies" asp-action="Update" asp-route-id="@movie.Id">Editar</a>
                            <a class="btn btn-danger" role="button" asp-controller="Movies" asp-action="ConfirmRemove" asp-route-id="@movie.Id">Remover</a>
                        </div>
                    </td>
                </tr>
            }
        }
    </tbody>
</table>

CinemaManager/Views/Movies/IndexForUser.cshtml
@model IEnumerable<MoviesModel>
@{
    ViewData["Title"] = "Filmes";
}

<h1 class="display-4">Filmes</h1>

<table class="table" id="table">
    <thead>
        <tr>
            <th scope="col" style="width: 25%">Título</th>
            <th scope="col" style="width: 50%">Descrição</th>
            <th scope="col">Duração</th>
        </tr>
    </thead>

    <tbody>
        @if (Model is not null && Model.Any())
        {
            foreach (var movie in Model)
            {
                <tr class="align-middle">
                    <td>@movie.Title</td>
                    <td>@movie.Description</td>
                    <td>@movie.Duration</td>
                </tr>
            }
        }
    </tbody>
</table>

CinemaManager/Views/Movies/Update.cshtml
@model MoviesModel
@{
    ViewData["Title"] = "Editar Filme";
}

<h1 class="display-4">Editar Filme</h1>

@if (TempData["ErrorMessage"] is not null)
{
    <div class="alert alert-danger" role="alert">
        <span>@TempData["ErrorMessage"]</span>
        <button type="button" class="btn btn-danger btn-sm close-alert" arial-label="close">X</button>
    </div>
}

<form asp-controller="Movies" asp-action="Update" method="post">
    <div class="form-group">
        <label for="imageLink">Imagem</label>
        <input type="text" asp-for="Image" class="form-control" id="imageLink" placeholder="Link da Imagem">
        @Html.ValidationMessageFor(x => x.Image)
    </div>
    <br />

    <div class="form-group">
        <label for="title">Título</label>
        <input type="text" asp-for="Title" class="form-control" id="title" placeholder="Título do filme">
        @Html.ValidationMessageFor(x => x.Title)
    </div>
    <br />

    <div class="form-group">
        <label for="description">Descrição</label>
        <input type="text" asp-for="Description" class="form-control" id="description" placeholder="Descrição do filme">
        @Html.ValidationMessageFor(x => x.Description)
    </div>
    <br />

    <div class="form-group">
        <label for="duration">Duração</label>
        <input type="datetime" asp-for="Duration" class="form-control" id="duration" placeholder="Ex.: 30min ou 1h ou 1h 30min">
        @Html.ValidationMessageFor(x => x.Duration)
    </div>
    <br />

    <button type="submit" class="btn btn-primary form-control">Atualizar</button>
    <a class="btn btn-link form-control" role="button" asp-controller="Movies" asp-action="Index">Voltar</a>
</form>